---
- name: dci new job
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        topic: '{{ topic }}'
      register: job_informations

    - name: Set  global variables
      set_fact:
        job_id: '{{ job_informations["job_id"] }}'

- name: dci setup
  hosts: localhost
  vars:
    dci_status: 'new'
    components: "{{ job_informations['components'] }}"
  tasks:
    - block:
        - include: plays/new.yml
      rescue:
        - include: plays/failure.yml

- name: dci tests
  hosts: localhost
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include: plays/running.yml
      rescue:
        - include: plays/failure.yml

- name: dci teardown
  hosts: localhost
  vars:
    dci_status: 'success'
  tasks:
    - include: plays/teardown.yml
