---
- name: schedule new job
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        topic: '{{ topic }}'
      register: job_informations

    - name: Set  global variables
      set_fact:
        job_id: "{{ job_informations['job_id'] }}"
        component: "{{ job_informations['components'][0] }}"
        atomic_host_path: "/tmp/atomic_host_image.qcow2"
        tests_repository: "https://github.com/projectatomic/atomic-host-tests.git"
        tests_version: "ca78c6254fdecdc7f85241139fbfcee4992cecde"

- name: download latest component
  hosts: localhost
  tasks:
    - block:
        - include: dci/download.yml
      rescue:
        - include: dci/failure.yml

- name: clean environment
  hosts: localhost
  tasks:
    - block:
        - include: hooks/clean.yml
          vars:
            dci_status: 'pre-run'
      rescue:
        - include: dci/failure.yml

- name: install product
  hosts: localhost
  tasks:
    - block:
        - include: hooks/install.yml
          vars:
            dci_status: 'pre-run'
      rescue:
        - include: dci/failure.yml

- name: run test
  hosts: localhost
  tasks:
    - block:
        - include: hooks/test.yml
          vars:
            dci_status: 'running'
      rescue:
        - include: dci/failure.yml

- name: run DCI test
  hosts: localhost
  tasks:
    - block:
        - include: dci/test.yml
          vars:
            dci_status: 'running'
      rescue:
        - include: dci/failure.yml

- name: teardown
  hosts: localhost
  tasks:
    - include: dci/success.yml
