---
- name: schedule new job
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        topic: '{{ topic }}'
      register: job_informations

    - name: Set  global variables
      set_fact:
        job_id: "{{ job_informations['job_id'] }}"

- name: clean environment
  hosts: localhost
  tasks:
    - block:
        - include: hooks/clean.yml
          vars:
            dci_status: 'new'
      rescue:
        - include: hooks/failure.yml

- name: install product
  hosts: localhost
  tasks:
    - block:
        - include: hooks/install.yml
          vars:
            dci_status: 'pre-run'
            component: "{{ job_informations['components'][0] }}"
      rescue:
        - include: hooks/failure.yml

- name: run test
  hosts: localhost
  tasks:
    - block:
        - include: hooks/test.yml
          vars:
            dci_status: 'running'
      rescue:
        - include: hooks/failure.yml

- name: teardown
  hosts: localhost
  tasks:
    - include: hooks/success.yml
