---
- name: CHECK
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: check extra packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python-pip

    - name: check extra packages are installed
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"

- name: NEW JOB
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        topic: '{{ TOPIC_NAME }}'
      register: job_informations

    - name: set  global variables
      set_fact:
        job_id: "{{ job_informations['job_id'] }}"
        component: "{{ job_informations['components'][0] }}"
        rhel_image_path: "/tmp/{{ job_informations['components'][0]['name'] }}.qcow2"

- name: DOWNLOAD
  hosts: localhost
  vars:
    dci_status: 'new'
  tasks:
    - debug:
        msg: "{{ job_id }}"

    - debug:
        msg: "{{ component }}"

    - block:
        - include_tasks: dci/download.yml
      rescue:
        - include_tasks: dci/failure.yml

- name: CLEAN
  hosts: localhost
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - include_tasks: hooks/clean.yml
      rescue:
        - include_tasks: dci/failure.yml

- name: INSTALL
  hosts: localhost
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - include_tasks: hooks/install.yml
      rescue:
        - include_tasks: dci/failure.yml

- name: TESTS
  hosts: localhost
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: dci/test.yml
      rescue:
        - include_tasks: dci/failure.yml

- name: SUCCESS
  hosts: localhost
  vars:
    dci_status: 'success'
  tasks:
    - include_tasks: dci/success.yml
