---
- name: schedule new job
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        topic: '{{ topic }}'
      register: job_informations

    - name: Set  global variables
      set_fact:
        job_id: '{{ job_informations["job_id"] }}'

- name: clean environment
  hosts: localhost
  vars:
    dci_status: 'new'
    components: "{{ job_informations['components'] }}"
  tasks:
    - block:
        - include: hooks/clean.yml
      rescue:
        - include: hooks/failure.yml

- name: install product
  hosts: localhost
  vars:
    dci_status: 'pre-run'
    components: "{{ job_informations['components'] }}"
  tasks:
    - block:
        - include: hooks/install.yml
      rescue:
        - include: hooks/failure.yml

- name: run test
  hosts: localhost
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include: hooks/test.yml
      rescue:
        - include: hooks/failure.yml

- name: teardown
  hosts: localhost
  tasks:
    - include: hooks/success.yml
